#! /usr/bin/env bash
source bashlib

isIn() {
    local key=$1; shift

    for value
    do [[ $value = "$key" ]] && return; done
}

cd "${0%/*}/../../"

emit "Enumerating localization keys"
code=$(find Classes -type f -name '*.m' -exec gsed -rn 's/.*(NSLocalizedString|l)\(@("[^"]*").*/\2/p' {} + | sort -u)
for l in Resources/English.lproj/Localizable.strings; do
    k=${l#*/}; k=${k%%/*}
    emit "   - $k"

    lang+=( "$k" )
    lproj+=( "$(sed -n 's/^\("[^"]*"\).*/\1/p' "$l" | sort -u)" )
done

healthy=1
echo; emit "Looking for unused localization keys"
for l in ${!lang[@]}; do
    while read; do
        healthy=0
        emit -y "   ${lang[l]}: ${REPLY##*([[:space:]])} "
    done < <(comm -1 -3 <(printf '%s\n' "$code") <(printf '%s\n' "${lproj[l]}"))
done
(( healthy )) && emit "All good."

echo; emit "Looking for missing localization keys"
for l in ${!lang[@]}; do
    while read; do
        healthy=0
        emit -r "   ${lang[l]}: ${REPLY##*([[:space:]])} "
    done < <(comm -2 -3 <(printf '%s\n' "$code") <(printf '%s\n' "${lproj[l]}"))
done
(( healthy )) && emit "All good."
